// Generated by CoffeeScript 1.7.1
(function() {
  var maotama;

  maotama = angular.module('maotama', ['ngRoute', 'ngSanitize', 'maotama.filters', 'maotama.services', 'maotama.directives', 'maotama.controllers']);

  maotama.config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/apps/:app_id', {
        templateUrl: 'partials/app_show.html',
        controller: 'AppsShowController'
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=app.map
