// Generated by CoffeeScript 1.7.1
(function() {
  var humanize, languages, markdown;

  languages = require('./js/languages.json');

  humanize = require('humanize');

  markdown = require("markdown").markdown;

  angular.module('maotama.filters', []).filter('language_translate', function() {
    return function(input) {
      return languages[input];
    };
  }).filter('filesize', function() {
    return humanize.filesize;
  }).filter('markdown', function() {
    return function(input) {
      if (input) {
        return markdown.toHTML(input);
      }
    };
  });

}).call(this);

//# sourceMappingURL=filters.map
