// Generated by CoffeeScript 1.7.1
(function() {
  var humanize, languages;

  languages = require('./js/languages.json');

  humanize = require('humanize');

  angular.module('maotama.filters', []).filter('language_translate', function() {
    return function(input) {
      return languages[input];
    };
  }).filter('filesize', function() {
    return humanize.filesize;
  });

}).call(this);

//# sourceMappingURL=filters.map
